[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SUPABASE_URL = "https://yhratzeatsvajrpydrok.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlocmF0emVhdHN2YWpycHlkcm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjAwMjksImV4cCI6MjA3NDIzNjAyOX0.Hp3X_81RHB7IHGOflZjdIK4Oi-7Oh1UTfXBWIncuiwQ"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://yhratzeatsvajrpydrok.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlocmF0emVhdHN2YWpycHlkcm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjAwMjksImV4cCI6MjA3NDIzNjAyOX0.Hp3X_81RHB7IHGOflZjdIK4Oi-7Oh1UTfXBWIncuiwQ"